
=================================== ERRORS ====================================
________________________ ERROR collecting test session ________________________
C:\Users\SEDUC\Desktop\PROJETOS\omni_gerador_artigos\venv\Lib\site-packages\_pytest\config\__init__.py:642: in _importconftest
    mod = import_path(conftestpath, mode=importmode, root=rootpath)
C:\Users\SEDUC\Desktop\PROJETOS\omni_gerador_artigos\venv\Lib\site-packages\_pytest\pathlib.py:565: in import_path
    importlib.import_module(module_name)
C:\Program Files\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1206: in _gcd_import
    ???
<frozen importlib._bootstrap>:1178: in _find_and_load
    ???
<frozen importlib._bootstrap>:1149: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
C:\Users\SEDUC\Desktop\PROJETOS\omni_gerador_artigos\venv\Lib\site-packages\_pytest\assertion\rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests\integration\conftest.py:7: in <module>
    from domain.models import ArticleOutput
domain\models.py:10: in <module>
    from .orm_models import *
E   ModuleNotFoundError: No module named 'domain.orm_models'
=========================== short test summary info ===========================
ERROR .. - ModuleNotFoundError: No module named 'domain.orm_models'
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
1 error in 1.23s
